services:
  php-backend:
    build:
      context: ./php-backend
      dockerfile: Dockerfile
    container_name: php-backend
    volumes:
      - ./php-backend:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    working_dir: 
      /var/www/html

  react-frontend:
    build: ./react-frontend
    container_name: react-frontend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    depends_on:
      - php-backend
      - react-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./postgresql-database/data-base-init:/docker-entrypoint-initdb.d
      - ./postgresql-database/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
