version: '3.8'

services:
  php-backend:
    build:
      context: ./php-backend/app
      dockerfile: Dockerfile
    container_name: php-backend
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./php-backend/app/skeleton:/var/www/html
    networks:
      - app-network
    environment:
      - DATABASE_URL=pgsql://user:password@db:5432/mydb
      - APP_ENV=prod
      - APP_SECRET=your_secret_key

  react-frontend:
    build: ./react-frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./postgresql-database/db-init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
