version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./postgresql-database/db-init:/docker-entrypoint-initdb.d
      - ./postgresql-database/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  rest-api:
    build:
      context: ./php-backend
      dockerfile: Dockerfile-rest-api
    container_name: rest-api
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - ./php-backend:/var/www/html  # Для синхронизации локальных изменений с контейнером (если нужно)
    depends_on:
      - db
    networks:
      - app-network

  ws-server:
    build:
      context: ./php-backend
      dockerfile: Dockerfile-ws-server
    container_name: ws-server
    depends_on:
      - db
    ports:
      - "9090:9090"
    networks:
      - app-network

  react-frontend:
    build: 
      context: ./react-frontend
      dockerfile: Dockerfile-frontend
    container_name: react-frontend
    environment:
      REACT_APP_API_URL: "http://localhost:8080"
      REACT_APP_WS_URL: "ws://localhost:9090"
    ports:
      - "3000:3000"
    depends_on:
      - rest-api
      - ws-server
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
