version: '3.8'

services:
  # php-backend:
  #   build:
  #     context: ./php-backend
  #     dockerfile: Dockerfile
  #   container_name: php-backend
  #   volumes:
  #     - ./php-backend:/var/www/html
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"  # Проброс порта 8080
  #   networks:
  #     - app-network
  #   working_dir: /var/www/html

  # react-frontend:
  #   build: ./react-frontend
  #   container_name: react-frontend
  #   networks:
  #     - app-network
  #   # Порт не экспонируется, так как Nginx обслуживает статические файлы

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./postgresql-database/db-init:/docker-entrypoint-initdb.d
      - ./postgresql-database/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
