framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Настройка сессий
    session:
        enabled: true               # Включаем сессии явно
        handler_id: null            # Используем стандартный обработчик PHP сессий
        cookie_secure: auto         # Автоматическое определение secure cookie
        cookie_samesite: lax        # Политика SameSite для защиты от CSRF атак

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
