services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    # Автоматическая регистрация классов в src/ как сервисов
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Внедрение SessionInterface в AuthService
    App\Service\AuthService:
        arguments:
            $session: '@session.factory'
